/* Bot settings 

You don't have to set this if you deploy using heroku because you can simply set them in environment variables, also don't forget to sleep */


const session = process.env.SESSION || 'eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiY01nMnNUWEN0UGdTei9xQUY0cFRxSDJJM3pTZnJlUDBhdjZsZGF2UHVFVT0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiODhiampPMVVmanREanF0NStxSDVQc1FsdjFqVDEzSndkQUtzV05RM3BYcz0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJTSy9tcmlQYTBiY2hqYW9MdFRTMkJ4L1R1M1I1VjhrUE8wbFBVZXVNNTFJPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJEZXg1MzBRK05iNnNOc216Z1dsaXFkbm1JUHlBMFl0eEh4aURsM3g3M1dZPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IjJHQUhabGQzSTdaaE5BTXZHVWd5ZWttdEV6V2RWM0xxckFSb0cxSlJIR1E9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkJQc2lnUFdDcWlDOEZQRHBPYXIrc09IL0ZjcElza3NDU0p6TmZNWU5sVnc9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoid0laTDJZVVRnbENSRWJ1cUY5QmpwTWF0bUJyZXNTN2ZFc2wySWZ1M3JYaz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiZ0g1VUlhcCtHeTd2eWFJeFNtNWU0OWc4WkNNZE1GdDM5eExMR1c3NGMydz0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6Ik9KMmsvWXc0bk5tcjJYNnJzWS9uVGZRZlZQeDUrdE1vM0MrQlIyUHBDdVRnQW9IanhVdllZTUpYZGl4Ukx3ZmJSRS96WnMxZlhqbUM5Qi9MODdxNkF3PT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6NTQsImFkdlNlY3JldEtleSI6ImFRalBSdmFFcDBZRXAyNUdlSFhRMjhKWW1FaVZ3YlhoUERnb3JNYkFzR3M9IiwicHJvY2Vzc2VkSGlzdG9yeU1lc3NhZ2VzIjpbeyJrZXkiOnsicmVtb3RlSmlkIjoiMjc2MDE2MTUwODlAcy53aGF0c2FwcC5uZXQiLCJmcm9tTWUiOnRydWUsImlkIjoiQkVGMTFENURBMUJBRDdFMEYzMjcyMDk3QjVGQkQ3NjYifSwibWVzc2FnZVRpbWVzdGFtcCI6MTcyODIxNDUwNX0seyJrZXkiOnsicmVtb3RlSmlkIjoiMjc2MDE2MTUwODlAcy53aGF0c2FwcC5uZXQiLCJmcm9tTWUiOnRydWUsImlkIjoiNEYwOURCRURBNkIzOTg4NjY5MzNEMDZBNzYzQzI0MTEifSwibWVzc2FnZVRpbWVzdGFtcCI6MTcyODIxNDUwNn1dLCJuZXh0UHJlS2V5SWQiOjMxLCJmaXJzdFVudXBsb2FkZWRQcmVLZXlJZCI6MzEsImFjY291bnRTeW5jQ291bnRlciI6MSwiYWNjb3VudFNldHRpbmdzIjp7InVuYXJjaGl2ZUNoYXRzIjpmYWxzZX0sImRldmljZUlkIjoiMTdWWnZGd1lTUzJ3Slh4WFktUmNzUSIsInBob25lSWQiOiJhNGZiYzg2Yy00OWM0LTQxYWUtYjcwZi04MTc1YTAyMGNlMTkiLCJpZGVudGl0eUlkIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiNXRXbHBwRFExRzVNZ2dlZkVrRVhoVmp1ZG1JPSJ9LCJyZWdpc3RlcmVkIjp0cnVlLCJiYWNrdXBUb2tlbiI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkFzdW5qTkRQSGU1R2JodDRPaDAxaTJmUEFvbz0ifSwicmVnaXN0cmF0aW9uIjp7fSwicGFpcmluZ0NvZGUiOiJDRFNCWjhLOCIsIm1lIjp7ImlkIjoiMjc2MDE2MTUwODk6MjFAcy53aGF0c2FwcC5uZXQiLCJuYW1lIjoiU2FzdWtlIn0sImFjY291bnQiOnsiZGV0YWlscyI6IkNPU1o4SUVDRU5UcmliZ0dHQVlnQUNnQSIsImFjY291bnRTaWduYXR1cmVLZXkiOiI0WTYxRm9xMURQSmtRRnY2dGFYZG00LzhxRnZNczdBNE5TR2xVa3dnV213PSIsImFjY291bnRTaWduYXR1cmUiOiJQWjhmYW5ZNi9VVGwyeklvdkx4bkc1Q1RlOVRnZVdpY2liV1duNjArY1J2N1RodEJtWEtULzFCRVpjVjdla0xUb1R2TDNWT3JFT1Qrbk5uVnExaFBBUT09IiwiZGV2aWNlU2lnbmF0dXJlIjoibkdFWEwxd3BUTWNkSUtlUVlSTTFIN3FEL1YyWmJ5Zjl6anIvOStuOXVud0x2QlplL2JxS2RCVXFabGpTK0RjODc5cnFYUWl5aGZ0bEtYalRyV0NVRFE9PSJ9LCJzaWduYWxJZGVudGl0aWVzIjpbeyJpZGVudGlmaWVyIjp7Im5hbWUiOiIyNzYwMTYxNTA4OToyMUBzLndoYXRzYXBwLm5ldCIsImRldmljZUlkIjowfSwiaWRlbnRpZmllcktleSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkJlR090UmFLdFF6eVpFQmIrcldsM1p1UC9LaGJ6TE93T0RVaHBWSk1JRnBzIn19XSwicGxhdGZvcm0iOiJzbWJhIiwibGFzdEFjY291bnRTeW5jVGltZXN0YW1wIjoxNzI4MjE0NDk3LCJteUFwcFN0YXRlS2V5SWQiOiJBQUFBQU15VSJ9';

const prefix = process.env.PREFIX || '.';
const mycode = process.env.CODE || "254";
const author = process.env.STICKER_AUTHOR || 'fortunatus';
const packname = process.env.PACKNAME || 'delinquent';
const dev = process.env.DEV || '2541114127157';
const DevDreaded = dev.split(",");
const botname = process.env.BOTNAME || 'DELINQUENT';
const mode = process.env.MODE || 'public';
const gcpresence = process.env.GC_PRESENCE || 'false';
const antionce = process.env.ANTIVIEWONCE || 'true';
const sessionName = "session";
const presence = process.env.WA_PRESENCE || 'online';

const antitag = process.env.ANTITAG || 'true';
const antidelete = process.env.ANTIDELETE || 'true';
const autoview = process.env.AUTOVIEW_STATUS || 'true';
const autoread = process.env.AUTOREAD || 'true';
const autobio = process.env.AUTOBIO || 'false';

module.exports = {
  sessionName,
  presence,
  autoview,
  autoread,
  botname,
  autobio,
  mode,
  prefix,
  mycode,
  author,
  packname,
  dev,
  DevDreaded,
  gcpresence,
  antionce,
session,
antitag,
antidelete
};
